<a href="https://colab.research.google.com/github/marvinxu-free/Algorithm/blob/master/tensorflow2_chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TersorFlow-2.0-Quick-Start-Guide

## 第一章： eager变量&神经网络数学基础

TensorFlow2教程-Keras概述
Keras 是一个用于构建和训练深度学习模型的高阶 API。它可用于快速设计原型、高级研究和生产。

Keras的3个优点： 方便用户使用、模块化和可组合、易于扩展

In [1]:
import tensorflow as tf


In [2]:
print(f"tensorflow version is {tf.__version__}")
print(f"tensorflow eager execution is {tf.executing_eagerly()}")
print(f"keras version is {tf.keras.__version__}")

tensorflow version is 2.2.0
tensorflow eager execution is True
keras version is 2.3.0-tf


### 检查GPU是否存在

In [3]:
var = tf.Variable([3,2])

if tf.test.is_gpu_available():
  print("Running on GPU")
  print("GPU #0?")
  print(var.device.endwith("GPU:0"))
else:
  print("Running on CPU")
  

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
Running on CPU


### tensoflow变量

Tensorflow支持所有你希望使用到的数据类型， 比如:`tf.int32, tf.float64, tf.complex64`

[所有支持的数据类型在](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)

默认的整数类型是`tf.int32`，默认的实数类型为`tf.float32`。


In [4]:
t0 = 24 # constant variable
t1 = tf.Variable(42) # tensor
t2 = tf.Variable([[0.,1.,2.],[3.,6.,1.]]) # tensor

In [5]:
t0, t1, t2

(24,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
 array([[0., 1., 2.],
        [3., 6., 1.]], dtype=float32)>)

In [6]:
t1.assign(60)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=60>

In [7]:
t1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=60>

In [8]:
t1.dtype

tf.int32

#### **tensorflow常量**

In [9]:
v_cont = tf.constant(42)
v_cont

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [10]:
v_cont.numpy()

42

#### 变量的rank

In [12]:
tf.rank(t2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [13]:
t3 = tf.Variable([ [ [0., 1., 2.], [3., 4., 5.] ], [ [6., 
7., 8.], [9., 10., 11.] ] ]) # tensor variable

In [14]:
tf.rank(t3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#### **变量的shape**

In [15]:
tf.shape(t3)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 2, 3], dtype=int32)>

**tensor经常要做reshape操作，reshepe操作需要保证数据量size不变，这个操作在NN里面很常见**

In [16]:
r1 = tf.reshape(t3, [2,6]) # 2 rows 6 cols

In [17]:
tf.shape(r1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 6], dtype=int32)>

In [18]:
r1

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.]], dtype=float32)>

In [19]:
tf.Tensor.get_shape(r1)

TensorShape([2, 6])

#### **tensor数据切片**

In [20]:
t3

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

In [21]:
t3[1,0,2]

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

#### **获取tensor元素的个数**

In [22]:
tf.size(t3)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

**tensor元素转Numpy数值**

In [23]:
t3.numpy()

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)

#### **通过重载运算符，实现按元素自动乘积**

In [24]:
t3 * t3

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]], dtype=float32)>

#### **tensorflow 变量支持广播计算机制**

In [25]:
t3 * 4

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[ 0.,  4.,  8.],
        [12., 16., 20.]],

       [[24., 28., 32.],
        [36., 40., 44.]]], dtype=float32)>

#### 
**TensorFlow的常量、矩阵转置、矩阵乘法均是eager模式计算**

In [26]:
u = tf.constant([[1,2,3,4]])
v = tf.constant([[2,3,4,0]])
tf.matmul(u, tf.transpose(v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[20]], dtype=int32)>

**数据类型转换**

In [27]:
t4 = tf.Variable(3.0)

In [28]:
tf.cast(t4, dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

#### **参差不齐的变量**

In [29]:
ragged =tf.ragged.constant([[5, 2, 6, 1], [], [4, 10, 7], [8], [6,7]])

In [34]:
print(ragged)
print(ragged[0,:].numpy())
print(ragged[1,:])
print(ragged[2,:])

<tf.RaggedTensor [[5, 2, 6, 1], [], [4, 10, 7], [8], [6, 7]]>
[5 2 6 1]
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([ 4 10  7], shape=(3,), dtype=int32)


### 一些有用的函数

#### 平方差:tf.math,squared_difference

用来计算均方误差

In [35]:
x = [1,2,3,4,5]
y = 6
s = tf.math.squared_difference(x, y)
s

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([25, 16,  9,  4,  1], dtype=int32)>

In [42]:
a = [1,2,3,4]
b = [4,5,6,7]
tf.math.squared_difference(a, b)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 9, 9, 9], dtype=int32)>

#### tf.reduce_mean(input_tensor, axis=None, keepdims=None,name=None)

计算逻辑与np.mean一致，不过返回的数据类型与输入的tensor一致，而np.mean可以指定返回的数据类型

In [36]:
t3

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>

**在所有axes上求均值，相当于对所有的元素求均值**

In [37]:
tf.reduce_mean(t3)

<tf.Tensor: shape=(), dtype=float32, numpy=5.5>

**对axis=1求均值，也就是在axis=1的维度上汇总求均值，默认不保留维度，因此计算后的维度为[2,3]**

In [38]:
tf.reduce_mean(t3, axis=1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.5, 2.5, 3.5],
       [7.5, 8.5, 9.5]], dtype=float32)>

**对axis=1求均值，也就是在axis=1的维度上汇总求均值，保留维度，因此计算后的维度为[2,1,3]**

In [39]:
tf.reduce_mean(t3, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1, 3), dtype=float32, numpy=
array([[[1.5, 2.5, 3.5]],

       [[7.5, 8.5, 9.5]]], dtype=float32)>

**其它的维度同理，比如对aixs=0汇总求均值，保留或者不保留axis**

可以理解为对列求均值

In [40]:
tf.reduce_mean(t3, axis=0)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[3., 4., 5.],
       [6., 7., 8.]], dtype=float32)>

In [41]:
tf.reduce_mean(t3, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[3., 4., 5.],
        [6., 7., 8.]]], dtype=float32)>

#### 随机方法

##### **正太分布随机**

In [43]:
tf.random.normal(shape=(2,2,1), mean=0,
                 stddev=0.1, dtype=tf.float32,
                 seed = 1024, name='tf_normal_distribution'
                 )

<tf.Tensor: shape=(2, 2, 1), dtype=float32, numpy=
array([[[-0.08391493],
        [ 0.00524457]],

       [[ 0.00148488],
        [ 0.10044087]]], dtype=float32)>

##### **均匀分布**

In [45]:
tf.random.uniform(shape=(2,2,1), maxval=10, minval=1, dtype=tf.float16)

<tf.Tensor: shape=(2, 2, 1), dtype=float16, numpy=
array([[[7.3  ],
        [8.734]],

       [[4.367],
        [6.61 ]]], dtype=float16)>

##### 两次运行复现随机结果
保证两次运行的时候随机的结果一致。下面的代码不能保证rand1和rand2一致，因为两个在一次运行之间

In [52]:
tf.random.set_seed(11)
rand1 = tf.random.uniform(shape=(2,2), minval=1, maxval=100,
                          dtype=tf.int32)
rand2 = tf.random.uniform(shape=(2,2), minval=1, maxval=100,
                          dtype=tf.int32)
print(rand1)
print(rand2)

tf.Tensor(
[[ 2 49]
 [ 5 60]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[79 58]
 [62  2]], shape=(2, 2), dtype=int32)


In [53]:
tf.random.set_seed(11)
rand1 = tf.random.uniform(shape=(2,2), minval=1, maxval=100,
                          dtype=tf.int32)
rand2 = tf.random.uniform(shape=(2,2), minval=1, maxval=100,
                          dtype=tf.int32)
print(rand1)
print(rand2)

tf.Tensor(
[[ 2 49]
 [ 5 60]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[79 58]
 [62  2]], shape=(2, 2), dtype=int32)


##### 模拟骰子随机结果

要求：两个骰子，每个扔十次，模拟十次扔骰子的结果，并将结果保存到10 x3 的矩阵内部

In [54]:
dice1 = tf.Variable(tf.random.uniform((10,1), minval=1, 
                                      maxval=7, dtype=tf.int32))
dice2 = tf.Variable(tf.random.uniform((10,1), minval=1, 
                                      maxval=7, dtype=tf.int32))

dice_sum = dice1 + dice2 # element-wise
print(dice_sum)

result = tf.concat([dice1, dice2, dice_sum], axis=1)
print(result)

tf.Tensor(
[[10]
 [ 7]
 [ 8]
 [ 6]
 [ 5]
 [ 5]
 [ 6]
 [10]
 [ 6]
 [ 5]], shape=(10, 1), dtype=int32)
tf.Tensor(
[[ 5  5 10]
 [ 4  3  7]
 [ 5  3  8]
 [ 3  3  6]
 [ 1  4  5]
 [ 4  1  5]
 [ 5  1  6]
 [ 6  4 10]
 [ 3  3  6]
 [ 2  3  5]], shape=(10, 3), dtype=int32)


#### 输出对应axis的最大值对应的index

In [56]:
print(tf.argmax(result))
print(tf.argmax(result, axis=1))

tf.Tensor([7 0 0], shape=(3,), dtype=int64)
tf.Tensor([2 2 2 2 2 2 2 2 2 2], shape=(10,), dtype=int64)


#### 洛伦兹（Lorenz）系统

In [57]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [59]:
# rho = 28.0
# sigma = 10.0
# beta = 8.0/3.0

# def lorenz_equation(state, t):
#   x, y, z = tf.unstack(state) # pop parameters off the  stack
#   dx = sigma * (y - x)
#   dy = x * (rho - z) - y
#   dz = x * y - beta * z
#   return tf.stack([dx, dy, dz]) # push parameters onto a stack

# init_state = tf.constant([0, 2, 20], dtype=tf.float64)
# time_intervals = np.linspace(0, 50, num=5000)
# tensor_state = tf.math.special.odeint(lorenz_equation, init_state, time_intervals, full_output=False)
# x, y, z = tf.transpose(a=tensor_state)

# plt.plot(x, z)

#### 保存和恢复变量

In [65]:
num1 = tf.Variable(tf.random.uniform([10,10], minval=1, maxval=100, dtype=tf.int32))

In [67]:
check_point = tf.train.Checkpoint(var=num1)
save_path = check_point.save("./vars")
num1.assign(tf.zeros([10,10], dtype=tf.int32))
num1

<tf.Variable 'Variable:0' shape=(10, 10) dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [69]:
check_point.restore(save_path)
num1

<tf.Variable 'Variable:0' shape=(10, 10) dtype=int32, numpy=
array([[ 6, 37, 52, 35, 51, 54, 90, 67, 48, 22],
       [54, 98, 32, 85, 72, 80, 10, 85,  3, 26],
       [57, 68, 29,  7, 17, 59, 39, 97,  4, 42],
       [81,  7, 26, 72, 68, 85, 68, 97, 16, 70],
       [91, 56, 68, 86, 18, 90, 64, 82, 43, 28],
       [45, 93,  3, 71, 92,  7, 62, 39, 79, 72],
       [66, 51, 50, 25, 65, 18, 72, 65, 27, 78],
       [14, 77,  7, 33,  9, 64, 32, 31, 84, 75],
       [25, 17, 64, 13, 41, 27,  1, 47, 63, 88],
       [51, 50, 49, 27, 47,  8, 86, 67, 22, 61]], dtype=int32)>

#### 从Python函数中生成一个TensorFlow计算图

In [72]:
def f1(x,y):
  return tf.reduce_mean(tf.multiply(x ** 2, 5) + y ** 2)

f2 = tf.function(f1)

x = tf.constant([1,2,3,4])
y = tf.constant([1,2,3,4])

print(f1(x,y).numpy())
print(f2(x,y).numpy())

45
45
